# docker-compose.yml
version: '3'
services:
  python_service:
    build:
      context: .
      dockerfile: dockerfile.python
      args:
        - BASE_IMAGE=python:3.9
        - APP_VERSION=7.0
    environment:
      - DEBUG=true
    image: anshuldevops/python_web:7.2

  node_service:
    build:
      context: .
      dockerfile: dockerfile.node
      args:
        - BASE_IMAGE=node:21
        - APP_NAME=my-nodejs-app-7
    environment:
      - NODE_ENV=development
    image: anshuldevops/node_web:7.2
